spring.application.name=demo-2
spring.devtools.restart.enabled=true
# Custom Property / ENV
# Override these values from environment variables if needed
# set AUTHOR_NAME="New Name"
# export AUTHOR_NAME="New Name"
author.name=Mahendra
author.email=mahendra@example.com