spring.application.name=demo3
management.endpoint.info.enabled=true

management.server.port=9000
management.endpoint.web.exposure.include=health,info,beans

management.info.env.enabled=true
management.info.java.enabled=true
management.info.os.enabled=true


