spring.application.name=demo3

management.server.port=9000
management.endpoint.web.exposure.include=health,info,beans,env

management.info.env.enabled=true
management.info.java.enabled=true
management.info.os.enabled=true


